---
- name: Ensure Docker CE is installed
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"

- name: Create the docker group
  become: true
  group:
    name: docker
    state: present

- name: Add users to the docker secondary group
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_ce_users }}"

- name: Reset ssh connection to allow user changes to affect current user
  meta: reset_connection

- name: Start the docker service
  become: true
  systemd:
    name: docker
    enabled: true
    state: started
