---
- name: Ensure ddcutil is installed
  become: true
  package:
    name: ddcutil
    state: present

- name: Ensure required kernel modules are loaded
  become: true
  copy:
    src: ddcutil.conf
    dest: /etc/modules-load.d/ddcutil.conf
    mode: u=r,g=r,o=r
