---
- name: "Ensure user {{ user.username }} exists"
  become: true
  ansible.builtin.user:
    name: "{{ user.username }}"
    state: present

- name: "Ensure SSH public key is present for user {{ user.username }}"
  become: true
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    key: "{{ user.ssh_pubkey }}"
    state: present
  when: user.ssh_pubkey | default(false)

- name: "Ensure user {{ user.username }} can sudo if allowed"
  become: true
  ansible.builtin.lineinfile:
    line: "{{ user.username }} ALL=(ALL) ALL"
    path: "/etc/sudoers.d/{{ user.username }}"
    mode: "u=r,g=r,o="
    create: true
    validate: "visudo -cf %s"
    state: "{{ 'present' if user.sudoer | default(false) else 'absent' }}"

- name: "Ensure the password for user {{ user.username }} is set"
  become: true
  ansible.builtin.user:
    name: "{{ user.username }}"
    password: "{{ user.password }}"
    state: present
  when: user.password | default(false)
