---
- name: Ensure systemd units are present
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/systemd/system/{{ item }}"
    mode: "u=r,g=r,o=r"
  loop:
    - healthcheck-heartbeat.service
    - healthcheck-heartbeat.timer
  notify: Reload systemd

- name: Flush handlers
  meta: flush_handlers

- name: Enable timer
  become: true
  systemd:
    name: healthcheck-heartbeat.timer
    enabled: true
    state: started
  tags:
    - molecule-notest
