---
- name: Ensure Bluez is installed
  become: true
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils

- name: Ensure Bluetooth service is enabled and started
  become: true
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
  tags:
    - molecule-notest
