---
- name: Ensure Bluez is installed
  become: true
  package:
    name:
      - bluez
      - bluez-utils

- name: Ensure Bluetooth service is enabled and started
  become: true
  service:
    name: bluetooth
    state: started
    enabled: true
