---
- name: Ensure Sanoid is installed
  become: true
  package:
    name: sanoid
    state: present

- name: Ensure configuration directory exists
  become: true
  file:
    path: /etc/sanoid/
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure configuration is present
  become: true
  template:
    src: sanoid.conf.j2
    dest: "/etc/sanoid/sanoid.conf"
    mode: "u=r,g=r,o=r"

- name: Ensure timer is enabled
  become: true
  service:
    name: sanoid.timer
    state: started
    enabled: true
