---
- name: Ensure Sanoid is installed
  become: true
  ansible.builtin.package:
    name: sanoid
    state: present

- name: Ensure configuration directory exists
  become: true
  ansible.builtin.file:
    path: /etc/sanoid/
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure configuration is present
  become: true
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: "/etc/sanoid/sanoid.conf"
    mode: "u=r,g=r,o=r"

- name: Ensure timer is enabled
  become: true
  ansible.builtin.service:
    name: sanoid.timer
    state: started
    enabled: true
  tags:
    - molecule-notest
