---
- name: Ensure Snapperoo is installed
  become: true
  become_user: aur_builder
  ansible.legacy.aur:
    name: snapperoo-git
    state: present

- name: Ensure Snapperoo configuration is present
  become: true
  template:
    src: snapperoo.json.j2
    dest: /etc/snapperoo.json
    mode: "u=r,g=r,o=r"

- name: Enable Snapperoo timers
  become: true
  systemd:
    name: "snapperoo@{{ item }}.timer"
    enabled: true
    state: started
  loop:
    - hourly
    - daily
    - weekly
    - monthly
