---
galaxy_info:
  author: Dan Nixon
  description: Adds a Systemd timer to update a healthchecks.io check
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
