---
- name: Ensure ethtool is installed
  become: true
  package:
    name: ethtool
    state: present

- name: Ensure systemd service is present
  become: true
  register: systemd_service_install
  copy:
    src: wol@.service
    dest: /usr/lib/systemd/system/wol@.service

- name: Reload systemd services
  become: true
  systemd:
    daemon_reload: true
  when: systemd_service_install.changed

- name: Enable Wake on Lan
  become: true
  service:
    name: "wol@{{ wol_interface }}"
    state: started
    enabled: true
