galaxy_info:
  author: dannixon
  description: Installs system inspection/monitoring tools
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
