---
driver:
  name: podman

platforms:
  - name: ubuntu
    image: ghcr.io/dannixon/ansible-molecule-testing:ubuntu
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra
