---
- name: Ensure console font is installed
  become: true
  package:
    name: terminus-font
    state: present

- name: Ensure colour output is enabled in pacman
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertafter: "^\\[options\\]"
    line: Color

- name: Ensure pacman parallel downloads are enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertafter: "^\\[options\\]"
    line: ParallelDownloads = 5

- name: Ensure paru is configured
  become: true
  ansible.builtin.template:
    src: paru.conf
    dest: /etc/paru.conf
    mode: "u=rw,g=rw,o=r"
