---
- name: Non-FQDN hostname
  debug:
    var: system_hostname

- name: Ensure hostname is set
  become: true
  copy:
    dest: /etc/hostname
    content: |
      {{ system_hostname }}

- name: Ensure local host entries are present
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "127.0.0.1 localhost"
    - "::1 localhost"
    - "127.0.1.1 {{ system_hostname }}"

- name: Ensure locale is generated
  become: true
  community.general.locale_gen:
    name: "{{ system_locale }}"

- name: Ensure locale is selected
  become: true
  copy:
    dest: /etc/locale.conf
    content: |
      LANG={{ system_locale }}

- name: Ensure keyboard layout is selected
  become: true
  copy:
    dest: /etc/vconsole.conf
    content: |
      KEYMAP={{ system_keymap }}

- name: Ensure timezone is selected
  become: true
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Ensure NTP service is enabled
  become: true
  service:
    name: systemd-timesyncd.service
    enabled: true
    state: started

- name: Ensure common tools are installed
  become: true
  package:
    name:
      - sudo
      - iproute2
    state: present

- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: true
