---
- name: Non-FQDN hostname
  debug:
    var: system_hostname

- name: Ensure hostname is set
  become: true
  copy:
    content: |
      {{ system_hostname }}
    dest: /etc/hostname
    mode: "u=rw,g=r,o=r"
  tags:
    - molecule-notest

- name: Ensure local host entries are present
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "127.0.0.1 localhost"
    - "::1 localhost"
    - "127.0.1.1 {{ system_hostname }}"
  tags:
    - molecule-notest

- name: Ensure locale is generated
  become: true
  community.general.locale_gen:
    name: "{{ system_locale }}"
  tags:
    - molecule-notest

- name: Ensure locale is selected
  become: true
  copy:
    content: |
      LANG={{ system_locale }}
    dest: /etc/locale.conf
    mode: "u=rw,g=r,o=r"

- name: Ensure console is configured
  become: true
  ansible.builtin.template:
    src: vconsole.conf
    dest: /etc/
    mode: "u=rw,g=r,o=r"
  notify: Reconfigure vconsole

- name: Ensure timezone is selected
  become: true
  community.general.timezone:
    name: "{{ system_timezone }}"
  tags:
    - molecule-notest

- name: Ensure NTP service is enabled
  become: true
  service:
    name: systemd-timesyncd.service
    enabled: true
    state: started
  tags:
    - molecule-notest

- name: Ensure common tools are installed
  become: true
  package:
    name:
      - sudo
      - iproute2
    state: present

- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: true

- name: Ensure system is rebooted
  become: true
  ansible.builtin.reboot:
    msg: Rebooting post system configuration (via Ansible)
  when: system_reboot
