---
- name: Ensure dnscrypt-proxy is installed
  become: yes
  package:
    name: dnscrypt-proxy
    state: present

- name: Ensure dnscrypt-proxy configuration is present
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dnscrypt-proxy/{{ item }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - blocked-names.txt
    - forwarding-rules.txt
    - dnscrypt-proxy.toml
  notify:
    - Restart dnscrypt-proxy

- name: Ensure the dnscrypt-proxy service is enabled and running
  become: yes
  service:
    name: dnscrypt-proxy
    state: started
    enabled: yes

- name: Ensure system resolver is configured
  become: yes
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    attributes: +i

- name: Ensure helper scripts are present
  become: yes
  copy:
    src: dnscrypt-proxy-blocked-count
    dest: /usr/sbin/
    mode: "u=rx,g=rx,o=rx"
