---
- name: Ensure APT key is added
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present

- name: Ensure APT repository is added
  become: true
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    filename: podman
    state: present

- name: Update APT repos
  become: true
  apt:
    update_cache: true

- name: Ensure Podman is installed
  become: true
  package:
    name: podman
    state: present
