---
- name: Ensure auditd is installed
  become: true
  ansible.builtin.package:
    name: audit
    state: present

- name: Ensure rules.d exists
  become: true
  ansible.builtin.file:
    path: /etc/audit/rules.d/
    mode: "u=rwx,g=rx,o="
    state: directory

- name: Ensure rules are present
  become: true
  ansible.builtin.copy:
    content: "{{ auditd_rules }}"
    dest: /etc/audit/rules.d/10-ansible-managed.rules
    mode: "u=r,g=r,o="
  notify:
    - Reload rules

- name: Ensure service is enabled and running
  become: true
  ansible.builtin.service:
    name: auditd.service
    state: started
    enabled: true
  tags:
    - molecule-notest
