---
- name: Ensure the user exists
  become: true
  ansible.builtin.user:
    name: "{{ interactive_user_username }}"
    state: present

- name: Ensure SSH public key is present
  become: true
  ansible.posix.authorized_key:
    user: "{{ interactive_user_username }}"
    key: "{{ interactive_user_ssh_key }}"
    state: present
  when: interactive_user_ssh_key | default(no)

- name: Ensure user can sudo if allowed
  become: true
  ansible.builtin.lineinfile:
    line: "{{ interactive_user_username }} ALL=(ALL) ALL"
    path: "/etc/sudoers.d/{{ interactive_user_username }}"
    mode: "u=r,g=r,o="
    create: true
    validate: "visudo -cf %s"
  when: interactive_user_sudoer

- name: Ensure the user's password is set
  become: true
  ansible.builtin.user:
    name: "{{ interactive_user_username }}"
    password: "{{ interactive_user_password }}"
    state: present
  when: interactive_user_password | default(no)
