---
- name: Set service name
  ansible.builtin.set_fact:
    tailscale_service_name: tailscale

- name: Ensure Tailscale is installed
  become: true
  ansible.builtin.package:
    name: tailscale
    state: present
