---
- name: Ensure APT key is added
  become: true
  ansible.builtin.apt_key:
    url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg"
    state: present

- name: Ensure APT repository is added
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Ensure Tailscale is installed
  become: true
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
    state: present
