---
- name: Ensure packages are installed
  become: true
  ansible.builtin.package:
    name:
      - acpi
      - bmon
      - dua-cli
      - hddtemp
      - htop
      - iftop
      - lm_sensors
      - powertop
      - smartmontools
      - tcpdump
      - upower
      - wireguard-tools
    state: present
