---
- name: Ensure packages are installed
  become: yes
  package:
    name:
      - acpi
      - hddtemp
      - htop
      - lm-sensors
      - powertop
      - smartmontools
      - upower
    state: present
