---
- name: Ensure pacages are installed
  become: true
  package:
    name:
      - acpi
      - hddtemp
      - htop
      - lm_sensors
      - powertop
      - smartmontools
      - upower
    state: present
