---
- name: Ensure Git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure Git user exists
  become: true
  ansible.builtin.user:
    name: git
    password: "!"
    shell: /usr/bin/git-shell
    update_password: always
    state: present

- name: Ensure SSH public keys are present
  become: true
  ansible.posix.authorized_key:
    user: git
    key: "{{ item }}"
    state: present
  loop: "{{ git_server_ssh_pubkeys }}"

- name: Ensure the intended data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ git_server_path }}"
    state: directory
    owner: git
    group: git
    mode: "u=rwx,g=rwx,o=rx"
