---
galaxy_info:
  author: dannixon
  description: Installs PipeWire and relevant compatibility libraries
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux

dependencies: []
