---
- name: Ensure requirements for building packages are satisfied
  become: true
  package:
    name: base-devel
    state: present

- name: Ensure a user exists to build packages
  become: true
  user:
    name: aur_builder
    create_home: false
    password: "!"

- name: Ensure the AUR builder user can use sudo without a password
  become: true
  lineinfile:
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    path: /etc/sudoers.d/aur_builder
    mode: "u=r,g=r,o="
    create: true
    validate: "visudo -cf %s"
