---
- name: Ensure requirements for building packages are satisfied
  become: true
  ansible.builtin.package:
    name: base-devel
    state: present

- name: Ensure a user exists to build packages
  become: true
  ansible.builtin.user:
    name: aur_builder
    password: "!"
    create_home: false
    home: /
    comment: User to automate building packages from the AUR

- name: Ensure the AUR builder user can use sudo without a password
  become: true
  ansible.builtin.lineinfile:
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    path: /etc/sudoers.d/aur_builder
    mode: "u=r,g=r,o="
    create: true
    validate: "visudo -cf %s"
