---
- name: Ensure requirements for building packages are satisfied
  become: true
  package:
    name: base-devel
    state: present

- name: Ensure a user exists to build packages
  become: true
  user:
    name: aur_builder
    group: wheel

- name: Ensure the AUR builder user can use sudo without a password
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"
