---
- name: Ensure iptables userland tools are not installed
  become: true
  ansible.builtin.package:
    name:
      - iptables
      - ufw
    state: absent

- name: Ensure nftables userland tools are installed
  become: true
  ansible.builtin.package:
    name: nftables
    state: present
