---
- name: Ensure nftables userland tools are installed
  become: true
  package:
    name:
      - nftables
      - iptables-nft
    state: present

- name: Ensure iptables services are disabled and stopped
  become: true
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - iptables
    - ip6tables
