---
- name: Set config file location
  ansible.builtin.set_fact:
    nftables_config_file: /etc/nftables.nft
  tags:
    - firewall_rules

- name: Ensure nftables userland tools are installed
  become: true
  ansible.builtin.package:
    name: nftables
    state: present
