---
- name: Ensure nftables is installed
  include_tasks: "{{ lookup('first_found', candidate_files) }}"
  vars:
    candidate_files:
      - "install_{{ ansible_distribution }}.yml"

- name: Ensure configuration is present
  become: true
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "u=r,g=r,o=r"
  notify:
    - Restart nftables
  tags:
    - firewall_rules

# Using `validate` in the above task does not work as (I believe) -c expects to
# check for updates to an existing file.
- name: Check nftables configuration
  become: true
  command: nft -c -f /etc/nftables.conf
  changed_when: false
  tags:
    - firewall_rules

- name: Ensure service is enabled and running
  become: true
  service:
    name: nftables
    enabled: true
    state: started
