---
- name: Install nftables
  include_tasks: "{{ lookup('first_found', candidate_files) }}"
  vars:
    candidate_files:
      - "install_{{ ansible_distribution }}.yml"

- name: Ensure configuration directory exists
  become: true
  file:
    path: /etc/nftables.conf.d
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure configuration fragments exist
  become: true
  copy:
    src: nftables.conf.d/
    dest: /etc/nftables.conf.d
    mode: "u=rw,g=r,o=r"
  tags:
    - firewall_rules
  notify:
    - Restart nftables

- name: Ensure nftables configuration is present
  become: true
  copy:
    src: "{{ lookup('first_found', candidate_files) }}"
    dest: /etc/nftables.conf
    mode: "u=rw,g=r,o=r"
  vars:
    candidate_files:
      - "{{ nftables_config_file }}"
      - default.nft
  tags:
    - firewall_rules
  notify:
    - Restart nftables

- name: Check nftables configuration
  become: true
  command: nft -c -f /etc/nftables.conf
  changed_when: false
  tags:
    - firewall_rules

- name: Ensure nftables service is enabled and running
  become: true
  service:
    name: nftables
    enabled: true
    state: started
