---
- name: Install nftables
  include_tasks: "{{ task_file }}"
  loop_control:
    loop_var: task_file
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"

- name: Ensure configuration directory exists
  become: true
  file:
    path: /etc/nftables.conf.d
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure configuration fragments exist
  become: true
  copy:
    src: nftables.conf.d/
    dest: /etc/nftables.conf.d
    mode: "u=rw,g=r,o=r"
  tags:
    - firewall_rules
  notify:
    - Restart nftables

- name: Ensure nftables configuration is present
  become: true
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "u=rw,g=r,o=r"
  tags:
    - firewall_rules
  notify:
    - Restart nftables

- name: Check nftables configuration
  become: true
  command: nft -c -f /etc/nftables.conf
  changed_when: false
  tags:
    - firewall_rules

- name: Ensure nftables service is enabled and running
  become: true
  service:
    name: nftables
    enabled: true
    state: started
