---
- name: Ensure PPP client is installed
  become: true
  package:
    name: ppp
    state: present

- name: Ensure systemd service is present
  become: true
  register: systemd_service_install
  template:
    src: pppoe@.service
    dest: /usr/lib/systemd/system/pppoe@.service
    mode: "u=rw,g=r,o=r"
  notify: Reload systemd

- name: Flush handlers
  meta: flush_handlers

- name: Ensure peer configuration is present
  become: true
  template:
    src: peer
    dest: "/etc/ppp/peers/{{ pppoe_peer_name }}"
    mode: "u=rw,g=r,o=r"

- name: Enable PPPoE
  become: true
  service:
    name: "pppoe@{{ pppoe_peer_name }}"
    enabled: true
  tags:
    - molecule-notest
