---
- name: Converge
  hosts: all

  vars:
    pppoe_peer_name: bt
    pppoe_peer_config:
      - noauth
      - nodetach
      - noipdefault
      - noproxyarp
      - noremoteip
      - defaultroute
      - maxfail 100
      - persist
      - nic-eth0
      - ifname wan0
      - user bthomehub@btbroadband.com
      - password x

  roles:
    - dannixon.system.pppoe
