---
- name: Mirror list URL
  ansible.builtin.debug:
    var: arch_mirrorlist_url

- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
  register: tempfile
  changed_when: false

- name: Download mirror list
  ansible.builtin.get_url:
    url: "{{ arch_mirrorlist_url }}"
    dest: "{{ tempfile.path }}"
    mode: "u=rw,g=,o="
  changed_when: false

- name: Enable all servers in downloaded mirror list
  ansible.builtin.replace:
    path: "{{ tempfile.path }}"
    regexp: "^#Server"
    replace: "Server"
  changed_when: false

- name: Ensure mirror list is up to date
  become: true
  ansible.builtin.copy:
    src: "{{ tempfile.path }}"
    remote_src: true
    dest: /etc/pacman.d/mirrorlist
    mode: "u=rw,g=r,o=r"

- name: Delete temporary file
  ansible.builtin.file:
    path: "{{ tempfile.path }}"
    state: absent
  changed_when: false
