---
- name: Converge
  hosts: all

  vars:
    sanoid_datasets:
      - path: data/home
        config:
          use_template: production
      - path: data/images
        config:
          use_template: production
          recursive: "yes"
          process_children_only: "yes"
      - path: data/images/win7
        config:
          hourly: 4

    sanoid_templates:
      - name: production
        config:
          autosnap: "yes"
          autoprune: "yes"
          frequently: 0
          hourly: 36
          daily: 30
          monthly: 3
          yearly: 0

  roles:
    - dannixon.sanoid
