#!/bin/sh

set -eo pipefail

# Get the name for each blocked request
# Group all queries for the same name together
# Count all occurrences of the same name
# Sort by the number of occurrences
# Display
awk '{print $4}' '/var/log/dnscrypt-proxy/blocked-names.log' \
  | sort \
  | uniq -c \
  | sort -nr \
  | less --quit-if-one-screen
