---
galaxy_info:
  author: Dan Nixon
  description: Configures and enables systemd-networkd
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
