---
- name: Ensure NetworkManager is installed
  become: yes
  package:
    name: networkmanager
    state: present

- name: Ensure NetworkManager service is enabled and running
  become: yes
  service:
    name: NetworkManager
    state: started
    enabled: yes
