---
- name: Find existing configuration files
  ansible.builtin.find:
    paths: /usr/lib/systemd/network/
    patterns: "{{ networkd_clean_pattern }}"
  register: config_files

- name: Remove existing configuration files
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ config_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  notify:
    - Restart networkd
