---
name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: ansible/ansible-lint@v25.4.0
